swagger: "2.0"
info:
  title: Minha Api
  description: Exemplo Api
  version: "0.0.1"
  contact:
    name: Jotape 
    email: email@email.com
    url: http://meusite.com
host: api.host.com
schemes:
  - https
basePath: /subdominio
produces: 
  - application/json
  - application/xml
paths:
  /rotas:
    get:
      responses:
        default:
          description: Problemas nas requisições
          
definitions: #Seus tipos customizaveis
  Cliente: # Nome do novo tipo
    type: object # Tipo que ele será
    properties: # Propriedades do novo tipo
      id: # Nome da propriedade
        type: integer # Tipo da propridade
        description: Identificador único do usuário. # descrição
      nome:
        type: string
        description: Nome do usuário.
  Error: # Criando um outro tipo "Error"
    type: object
    properties:
      code:
        type: integer
        description: Código do erro.
      message:
        type: string
        description: Mensagem referente ao erro.
