swagger: "2.0" #Versão do swagger a ser usado
info: #Informações, campo obrigatório.
  title: Minha Api #Obrigatório
  version: "0.0.1" #Obrigatório
paths: #se faz obrigatório ter ao menos uma rota
  /rotas: #não precisa ter o nome de rotas, esse campo se refere ao path no padrão unix.
    get:
      responses:
        default:
          description: Problemas nas requisições