swagger: "2.0"
info: #Informações, campo obrigatório.
  title: Minha Api #Obrigatório
  description: Exemplo Api #Opcional
  version: "0.0.1" #Obrigatório
  contact: #Opcional
    name: Jotape 
    email: email@email.com #Email completo e válido
    url: http://meusite.com #URL completa e válida.
host: api.host.com #Aqui você determina o seu dominio
schemes: #Opcional
  - https #Opções são o protocolo http e o websocket.
basePath: /subdominio #subdominio se houver
produces: # Aqui define o Content-Type
  - application/json
paths:
  /rotas:
    get:
      responses:
        default:
          description: Problemas nas requisições
