swagger: "2.0"
info:
  title: Minha Api
  version: "0.0.1"
paths: 
  /:
    get:
      responses:
        default:
          description: Problemas nas requisições
    post:
      responses:
        default:
          description: Problemas nas requisições
    options:
      responses:
        default:
          description: Problemas nas requisições
  /{id}/:
    get:
      responses:
        default:
          description: Problemas nas requisições
      parameters:
        - name: id
          in: path
          required: true
          type: integer
    put:
      responses:
        default:
          description: Problemas nas requisições
      parameters:
        - name: id
          in: path
          required: true
          type: integer
    patch:
      responses:
        default:
          description: Problemas nas requisições
      parameters:
        - name: id
          in: path
          required: true
          type: integer
    delete:
      responses:
        default:
          description: Problemas nas requisições
      parameters:
        - name: id
          in: path
          required: true
          type: integer