swagger: "2.0"
info:
  title: Minha Api
  version: "0.0.1"
paths: 
  /rotas{id}:
    get:
      responses:
        default:
          description: Problemas nas requisições
      parameters:
        - name: id
          in: path
          required: true
          type: integer