swagger: "2.0"
info:
  title: Minha Api
  description: Exemplo Api
  version: "0.0.1"
  contact:
    name: Jotape 
    email: email@email.com
    url: http://meusite.com
host: api.host.com
schemes:
  - https
basePath: /subdominio
produces: 
  - application/json  
paths:
  /rotas:
    get:
      summary: metodo get de rotas
      description: | #use o pipe para campos multiline
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam a erat vestibulum, accumsan leo sit amet, volutpat nibh. Morbi ullamcorper placerat nisl, nec dignissim turpis tincidunt id. Donec viverra pretium vestibulum. Fusce volutpat fermentum leo sed imperdiet. Praesent pulvinar lectus mattis, molestie leo a, aliquam sem. Maecenas tincidunt pellentesque nunc ac placerat. Nullam et dictum odio. Praesent condimentum dui a lacinia lobortis.
      tags: # tags ajudam na organização
        - GET ROTAS TAG
      responses:
        200:
          description: Uma Lista de usuários
          schema: # Você deve seguir a estrutura de Schema abaixo, para tipos customizáveis.
            type: array
            items:
              $ref: '#/definitions/Cliente' # Essa é a forma de referenciar um definitions
        400: # Você não precisa especificar um retorno se não quiser.
          description: Bad Request
        500: # Aqui se o retorno for de um tipo primitivo.
          description: Erro No servidor
          schema:
            type: integer
        default:
          description: Problemas nas requisições
          schema:
            $ref: '#/definitions/Error'
          
definitions:
  Cliente:
    type: object
    properties:
      id:
        type: integer
        description: Identificador único do usuário.
      nome:
        type: string
        description: Nome do usuário.
  Error:
    type: object
    properties:
      code:
        type: integer
        description: Código do erro.
      message:
        type: string
        description: Mensagem referente ao erro.